# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: local
  hooks:
  -   id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
  -   id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
